---
author: "Communication Progress"
description: "Website informativ mbi legjislacionin e Republikës së Shqipërisë"
email:
markdown: kramdown
permalink: /:categories/:title/
encoding: UTF-8
social:
title: Njoh ligjin
url: http://localhost:4000
